### ISSUE TITLE
QA: How i can write my own plugin?

### ISSUE THREAD

**Issue by liverbool** [helios-ag/ElFinderPHP#54]
I want to register my custom plugin, how i can?

**Comment by liverbool** [comment]
Ok, find the way to do:

```yaml
# https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/doc/advanced-configuration.md#plugins

connector:
    binds:
        event:
            - "callable"
```
